INSERT INTO
    TEMP_COMPARED_TABLE_COLUMNS
    (
    COD_COMPARED_COLUMN,
    COD_COMPARED_TABLE,
    COLUMN_NAME,
    IS_PK_ANY_SOURCE,
    HAS_SCHEMA_DIFFERENCE,
    EXISTS_ON_ALL_SOURCES
    )
    VALUES
    (?, ?, ?, ?, ?, ?)