INSERT OR REPLACE INTO TEMP_COMPARED_TABLE_COLUMNS
    (COD_COMPARED_TABLE, COLUMN_NAME, IS_PK_ANY_SOURCE, HAS_SCHEMA_DIFFERENCE, EXISTS_ON_ALL_SOURCES)
SELECT
    COD_COMPARED_TABLE,
    COLUMN_NAME,
    IS_PK_ANY_SOURCE,
    HAS_SCHEMA_DIFFERENCE,
    EXISTS_ON_ALL_SOURCES
FROM
(
WITH
column_pks AS (
    SELECT
        TABLE_NAME,
        COLUMN_NAME,
        CASE WHEN SUM(IS_PK) >= 1 THEN 1 ELSE 0 END AS IS_PK_ANY_SOURCE
    FROM
        TEMP_SOURCE_TABLE_COLUMNS
    GROUP BY TABLE_NAME, COLUMN_NAME
),
schema_diffs AS (
      SELECT
            TABLE_NAME,
            COLUMN_NAME,
            CASE WHEN
                    COUNT(DISTINCT (TYPE || '-' || NOT_NULL || '-' || IS_PK))
                   != (COUNT(1) / COUNT(DISTINCT SOURCE_ID))
                THEN 1 ELSE 0
            END AS HAS_SCHEMA_DIFFERENCE
     FROM TEMP_SOURCE_TABLE_COLUMNS
     GROUP BY TABLE_NAME, COLUMN_NAME
),
exists_on AS (
    SELECT
        TABLE_NAME,
        COLUMN_NAME,
        CASE WHEN COUNT(DISTINCT SOURCE_ID) > 1 THEN 1 ELSE 0 END AS EXISTS_ON_ALL_SOURCES
    FROM TEMP_SOURCE_TABLE_COLUMNS
    GROUP BY TABLE_NAME, COLUMN_NAME
)
SELECT
    t.COD_COMPARED_TABLE,
    t.COLUMN_NAME,
	COALESCE(c.IS_PK_ANY_SOURCE, 0) AS IS_PK_ANY_SOURCE,
    COALESCE(s.HAS_SCHEMA_DIFFERENCE, 0) AS HAS_SCHEMA_DIFFERENCE,
    COALESCE(e.EXISTS_ON_ALL_SOURCES, 0) AS EXISTS_ON_ALL_SOURCES
FROM
(
SELECT
    DISTINCT a.COD_COMPARED_TABLE, a.TABLE_NAME, b.COLUMN_NAME
FROM TEMP_COMPARED_TABLES a
     INNER JOIN TEMP_SOURCE_TABLE_COLUMNS b ON a.TABLE_NAME = b.TABLE_NAME
) t
LEFT JOIN column_pks c ON c.TABLE_NAME = t.TABLE_NAME AND c.COLUMN_NAME = t.COLUMN_NAME
LEFT JOIN schema_diffs s ON s.TABLE_NAME = t.TABLE_NAME AND s.COLUMN_NAME = t.COLUMN_NAME
LEFT JOIN exists_on e ON e.TABLE_NAME = t.TABLE_NAME AND e.COLUMN_NAME = t.COLUMN_NAME
WHERE
    t.COD_COMPARED_TABLE = ?
)