WITH
schema_diffs AS (
     SELECT
            TABLE_NAME,
            CASE WHEN
                    COUNT(DISTINCT (COLUMN_NAME || '-' || TYPE || '-' || NOT_NULL || '-' || IS_PK))
                   != (COUNT(1) / COUNT(DISTINCT SOURCE_ID))
                THEN 1 ELSE 0
            END AS HAS_SCHEMA_DIFFERENCE
     FROM TEMP_SOURCE_TABLE_COLUMNS
     GROUP BY TABLE_NAME
),
record_counts AS (
    SELECT
        TABLE_NAME,
        CASE WHEN COUNT(DISTINCT RECORD_COUNT) > 1 THEN 1 ELSE 0 END AS HAS_RECORD_COUNT_DIFFERENCE
    FROM TEMP_SOURCE_TABLES
    GROUP BY TABLE_NAME
)
SELECT
    t.TABLE_NAME,
    COALESCE(r.HAS_RECORD_COUNT_DIFFERENCE, 0) AS HAS_RECORD_COUNT_DIFFERENCE,
	COALESCE(s.HAS_SCHEMA_DIFFERENCE, 0) AS HAS_SCHEMA_DIFFERENCE
FROM (SELECT DISTINCT TABLE_NAME FROM TEMP_SOURCE_TABLES) t
LEFT JOIN schema_diffs s ON s.TABLE_NAME = t.TABLE_NAME
LEFT JOIN record_counts r ON r.TABLE_NAME = t.TABLE_NAME;